version: '3.8'
services:
  mongodb_container:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  island-report:
    container_name: island-report
    image: measureshelter/islandreport:1.0.0-SNAPSHOT
    ports:
      - 8081:8081
    environment:
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: /jwt/publicKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt
    links:
      - mongodb_container
  techfields-jwt:
    container_name: techfields-jwt
    image: measureshelter/jwt:1.0.0-SNAPSHOT
    ports:
      - 8082:8082
    environment:
      SMALLRYE_JWT_SIGN_KEY_LOCATION: /jwt/privateKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt
    links:
      - island-report
