version: '3.7'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  island-report:
    container_name: island-report
    image: measureshelter/islandreport:1.0.0-SNAPSHOT
    ports:
      - 8081:8081
    environment:
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: /jwt/publicKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt
    links:
      - mongo
  techfields-jwt:
    container_name: techfields-jwt
    image: measureshelter/jwt:1.0.0-SNAPSHOT
    ports:
      - 8082:8082
    environment:
      SMALLRYE_JWT_SIGN_KEY_LOCATION: /jwt/privateKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt
volumes:
  mongodb_data_container: